package com.ewing.busi.pay.model;

// Generated 2016-2-2 17:07:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderRefund generated by hbm2java
 */
public class PayHistory implements java.io.Serializable {

  private Integer id;
  private String bizId;
  private String busiType;
  private Integer busiId;
  private String payWay;
  private Integer customerId;
  private Integer userId;
  private String status;
  private String comment;
  private Date createTime;
  private Date lastUpdate;
  
  public PayHistory(Integer id, String bizId, String busiType, Integer busiId, String payWay,
      Integer customerId, Integer userId, String status, String comment, Date createTime,
      Date lastUpdate) {
    super();
    this.id = id;
    this.bizId = bizId;
    this.busiType = busiType;
    this.busiId = busiId;
    this.payWay = payWay;
    this.customerId = customerId;
    this.userId = userId;
    this.status = status;
    this.comment = comment;
    this.createTime = createTime;
    this.lastUpdate = lastUpdate;
  }
  
  public Integer getId() {
    return id;
  }
  public void setId(Integer id) {
    this.id = id;
  }
  public String getBizId() {
    return bizId;
  }
  public void setBizId(String bizId) {
    this.bizId = bizId;
  }
  public String getBusiType() {
    return busiType;
  }
  public void setBusiType(String busiType) {
    this.busiType = busiType;
  }
  public Integer getBusiId() {
    return busiId;
  }
  public void setBusiId(Integer busiId) {
    this.busiId = busiId;
  }
  public String getPayWay() {
    return payWay;
  }
  public void setPayWay(String payWay) {
    this.payWay = payWay;
  }
  public Integer getCustomerId() {
    return customerId;
  }
  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }
  public Integer getUserId() {
    return userId;
  }
  public void setUserId(Integer userId) {
    this.userId = userId;
  }
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }
  public String getComment() {
    return comment;
  }
  public void setComment(String comment) {
    this.comment = comment;
  }
  public Date getCreateTime() {
    return createTime;
  }
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }
  public Date getLastUpdate() {
    return lastUpdate;
  }
  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }
  
  
  

  
  

}
