package com.ewing.busi.collect.model;

// Generated 2016-2-2 17:07:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderCart generated by hbm2java
 */
public class CustomerCollect implements java.io.Serializable {

    private Integer id;
    private Integer customerId;
    private Integer resourceId;
    private String iseff;
    private Date createTime;
    private Date lastUpdate;

    public CustomerCollect() {
    }

    public CustomerCollect(Integer id, Integer customerId, Integer resourceId, String iseff,
            Date createTime, Date lastUpdate) {
        super();
        this.id = id;
        this.customerId = customerId;
        this.resourceId = resourceId;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Integer getResourceId() {
        return resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public String getIseff() {
        return iseff;
    }

    public void setIseff(String iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}