package com.ewing.busi.resource.model;

// Generated 2015-10-10 22:43:59 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * WebCatagoryParam generated by hbm2java
 */
public class WebCatagoryParam implements java.io.Serializable {

	private Integer id;
	private int categoryId;
	private String paramName;
	private String paramValue;
	private String rootParamName;
	private int rank;
	private String iseff;
	private Date createTime;
	private Date lastUpdate;

	public WebCatagoryParam() {
	}

	public WebCatagoryParam(int categoryId, String paramName, int rank,
			String iseff, Date createTime, Date lastUpdate) {
		this.categoryId = categoryId;
		this.paramName = paramName;
		this.rank = rank;
		this.iseff = iseff;
		this.createTime = createTime;
		this.lastUpdate = lastUpdate;
	}

	public String getRootParamName() {
		return rootParamName;
	}

	public void setRootParamName(String rootParamName) {
		this.rootParamName = rootParamName;
	}

	public int getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	public int getRank() {
		return this.rank;
	}

	public void setRank(int rank) {
		this.rank = rank;
	}

	public String getIseff() {
		return this.iseff;
	}

	public void setIseff(String iseff) {
		this.iseff = iseff;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getLastUpdate() {
		return this.lastUpdate;
	}

	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

}
