package com.ewing.busi.customer.model;

// Generated 2016-2-2 11:30:39 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

    /**
     * 
     */
    private Integer id;
    /**
     * 消费用户名称
     */
    private String name;
    /**
     * 用户密码
     */
    private String password;
    /**
     * 头像
     */
    private String headIcon;
    /**
     * 电话号码
     */
    private String phone;
    /**
     * 性别 0:男 1:女
     */
    private String sex;
    /**
     * 是否生效 0:没生效 1:生效
     */
    private String iseff;
    
    private Date createTime;
    private Date lastUpdate;

    public Customer() {
    }

    public Customer(String name, String password, String phone, String sex, String iseff,
            Date createTime, Date lastUpdate) {
        this.name = name;
        this.password = password;
        this.phone = phone;
        this.sex = sex;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Customer(String name, String password, String headIcon, String phone, String sex,
            String iseff, Date createTime, Date lastUpdate) {
        this.name = name;
        this.password = password;
        this.headIcon = headIcon;
        this.phone = phone;
        this.sex = sex;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getHeadIcon() {
        return this.headIcon;
    }

    public void setHeadIcon(String headIcon) {
        this.headIcon = headIcon;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getIseff() {
        return this.iseff;
    }

    public void setIseff(String iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
