package com.ewing.busi.order.model;

// Generated 2016-2-14 11:55:34 by Hibernate Tools 3.4.0.CR1

/**
 * OrderDetailView generated by hbm2java
 */
public class OrderDetailView implements java.io.Serializable {

    private Integer id;
    /**
     * 订单id
     */
    private Integer orderId;
    /**
     * 流水号
     */
    private String bizId;
    /**
     * 资源id，表web_resource主键
     */
    private Integer resourceId;
    /**
     * 产品数量
     */
    private Integer itemCount;
    /**
     * 产品单价s
     */
    private float unitPrice;
    /**
     * 运费
     */
    private float cargoPrice;
    /**
     * 总价
     */
    private float totalPrice;
    /**
     * 购物状态 0:待付款 1:待发货 2:待收货
     */
    private String status;

    /**
     * 是否有效
     */
    private String iseff;
    /**
     * 铲平名称
     */
    private String productName;

    /**
     * icon
     */
    private String icon;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrderId() {
        return orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public String getBizId() {
        return bizId;
    }

    public void setBizId(String bizId) {
        this.bizId = bizId;
    }

    public Integer getResourceId() {
        return resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public Integer getItemCount() {
        return itemCount;
    }

    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    public float getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(float unitPrice) {
        this.unitPrice = unitPrice;
    }

    public float getCargoPrice() {
        return cargoPrice;
    }

    public void setCargoPrice(float cargoPrice) {
        this.cargoPrice = cargoPrice;
    }

    public float getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(float totalPrice) {
        this.totalPrice = totalPrice;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIseff() {
        return iseff;
    }

    public void setIseff(String iseff) {
        this.iseff = iseff;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
