package com.ewing.busi.order.model;

// Generated 2016-2-2 17:07:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderRefund generated by hbm2java
 */
public class OrderRefund implements java.io.Serializable {

    private Integer id;
    private String bizId;
    private Integer orderId;
    private Integer orderDetailId;
    private String type;
    private Integer customerId;
    private Integer userId;
    private Integer resourceId;
    private Integer reasonType;
    private String reason;
    private String cargoCom;
    private String cargoNumber;
    private float refundMoney;
    private String provePicUrl;
    private String status;
    private String iseff;
    private Date createTime;
    private Date lastUpdate;

    public OrderRefund() {
    }

    public OrderRefund(Integer orderId, String bizId, Integer orderDetailId, String type, Integer customerId, Integer userId,
            Integer resourceId, Integer reasonType, String reason, float refundMoney, String provePicUrl, String status, String iseff,
            Date createTime, Date lastUpdate) {
        this.orderId = orderId;
        this.bizId = bizId;
        this.orderDetailId = orderDetailId;
        this.type = type;
        this.customerId = customerId;
        this.userId = userId;
        this.resourceId = resourceId;
        this.reasonType = reasonType;
        this.reason = reason;
        this.refundMoney = refundMoney;
        this.provePicUrl = provePicUrl;
        this.status = status;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public OrderRefund(Integer orderId, String bizId, Integer orderDetailId, String type, Integer customerId, Integer userId,
            Integer resourceId, Integer reasonType, String reason, String cargoCom, String cargoNumber, float refundMoney,
            String provePicUrl, String status, String iseff, Date createTime, Date lastUpdate) {
        this.orderId = orderId;
        this.bizId = bizId;
        this.orderDetailId = orderDetailId;
        this.type = type;
        this.customerId = customerId;
        this.userId = userId;
        this.resourceId = resourceId;
        this.reasonType = reasonType;
        this.reason = reason;
        this.cargoCom = cargoCom;
        this.cargoNumber = cargoNumber;
        this.refundMoney = refundMoney;
        this.provePicUrl = provePicUrl;
        this.status = status;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }
    
    public String getBizId() {
      return bizId;
    }

    public void setBizId(String bizId) {
      this.bizId = bizId;
    }

    public String getProvePicUrl() {
      return provePicUrl;
    }

    public void setProvePicUrl(String provePicUrl) {
      this.provePicUrl = provePicUrl;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getOrderDetailId() {
        return this.orderDetailId;
    }

    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public Integer getReasonType() {
        return this.reasonType;
    }

    public void setReasonType(Integer reasonType) {
        this.reasonType = reasonType;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }
    
    public String getCargoCom() {
      return cargoCom;
    }

    public void setCargoCom(String cargoCom) {
      this.cargoCom = cargoCom;
    }

    public String getCargoNumber() {
        return this.cargoNumber;
    }

    public void setCargoNumber(String cargoNumber) {
        this.cargoNumber = cargoNumber;
    }

    public float getRefundMoney() {
        return this.refundMoney;
    }

    public void setRefundMoney(float refundMoney) {
        this.refundMoney = refundMoney;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getIseff() {
        return this.iseff;
    }

    public void setIseff(String iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
