package com.ewing.busi.order.model;

// Generated 2016-2-2 17:07:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderRefund generated by hbm2java
 */
public class OrderRefund implements java.io.Serializable {

    private Integer id;
    private Integer orderId;
    private Integer orderDetailId;
    private char type;
    private Integer customerId;
    private Integer userId;
    private Integer resourceId;
    private Integer reasonType;
    private Integer reason;
    private Integer cargoNumber;
    private float refundMoney;
    private char status;
    private char iseff;
    private Date createTime;
    private Date lastUpdate;

    public OrderRefund() {
    }

    public OrderRefund(Integer orderId, Integer orderDetailId, char type, Integer customerId, Integer userId,
            Integer resourceId, Integer reasonType, Integer reason, float refundMoney, char status, char iseff,
            Date createTime, Date lastUpdate) {
        this.orderId = orderId;
        this.orderDetailId = orderDetailId;
        this.type = type;
        this.customerId = customerId;
        this.userId = userId;
        this.resourceId = resourceId;
        this.reasonType = reasonType;
        this.reason = reason;
        this.refundMoney = refundMoney;
        this.status = status;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public OrderRefund(Integer orderId, Integer orderDetailId, char type, Integer customerId, Integer userId,
            Integer resourceId, Integer reasonType, Integer reason, Integer cargoNumber, float refundMoney,
            char status, char iseff, Date createTime, Date lastUpdate) {
        this.orderId = orderId;
        this.orderDetailId = orderDetailId;
        this.type = type;
        this.customerId = customerId;
        this.userId = userId;
        this.resourceId = resourceId;
        this.reasonType = reasonType;
        this.reason = reason;
        this.cargoNumber = cargoNumber;
        this.refundMoney = refundMoney;
        this.status = status;
        this.iseff = iseff;
        this.createTime = createTime;
        this.lastUpdate = lastUpdate;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public Integer getOrderDetailId() {
        return this.orderDetailId;
    }

    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    public char getType() {
        return this.type;
    }

    public void setType(char type) {
        this.type = type;
    }

    public Integer getCustomerId() {
        return this.customerId;
    }

    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getResourceId() {
        return this.resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public Integer getReasonType() {
        return this.reasonType;
    }

    public void setReasonType(Integer reasonType) {
        this.reasonType = reasonType;
    }

    public Integer getReason() {
        return this.reason;
    }

    public void setReason(Integer reason) {
        this.reason = reason;
    }

    public Integer getCargoNumber() {
        return this.cargoNumber;
    }

    public void setCargoNumber(Integer cargoNumber) {
        this.cargoNumber = cargoNumber;
    }

    public float getRefundMoney() {
        return this.refundMoney;
    }

    public void setRefundMoney(float refundMoney) {
        this.refundMoney = refundMoney;
    }

    public char getStatus() {
        return this.status;
    }

    public void setStatus(char status) {
        this.status = status;
    }

    public char getIseff() {
        return this.iseff;
    }

    public void setIseff(char iseff) {
        this.iseff = iseff;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getLastUpdate() {
        return this.lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

}
