package com.ewing.busi.order.model;

// Generated 2016-2-2 17:07:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * OrderRefund generated by hbm2java
 */
public class OrderProcessHistory implements java.io.Serializable {

  private Integer id;
  private String bizId;
  private Integer busiType;
  private Integer busiId;
  private Integer customerId;
  private Integer userId;
  private String status;
  private String statusString;
  private String comment;
  private String iseff;
  private Date createTime;
  private Date lastUpdate;

  public OrderProcessHistory() {}

  public OrderProcessHistory(Integer id, String bizId, Integer busiType, Integer busiId,
      Integer customerId, Integer userId, String status, String statusString, String comment,
      String iseff, Date createTime, Date lastUpdate) {
    super();
    this.id = id;
    this.bizId = bizId;
    this.busiType = busiType;
    this.busiId = busiId;
    this.customerId = customerId;
    this.userId = userId;
    this.status = status;
    this.statusString = statusString;
    this.iseff = iseff;
    this.comment = comment;
    this.createTime = createTime;
    this.lastUpdate = lastUpdate;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getIseff() {
    return iseff;
  }

  public void setIseff(String iseff) {
    this.iseff = iseff;
  }

  public String getBizId() {
    return bizId;
  }

  public void setBizId(String bizId) {
    this.bizId = bizId;
  }

  public Integer getBusiType() {
    return busiType;
  }

  public void setBusiType(Integer busiType) {
    this.busiType = busiType;
  }

  public Integer getBusiId() {
    return busiId;
  }

  public void setBusiId(Integer busiId) {
    this.busiId = busiId;
  }

  public Integer getCustomerId() {
    return customerId;
  }

  public void setCustomerId(Integer customerId) {
    this.customerId = customerId;
  }

  public Integer getUserId() {
    return userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getStatusString() {
    return statusString;
  }

  public void setStatusString(String statusString) {
    this.statusString = statusString;
  }

  public String getComment() {
    return comment;
  }

  public void setComment(String comment) {
    this.comment = comment;
  }

  public Date getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  public Date getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }



}
