package com.ewing.busi.sysparam.model;

import java.util.Date;

// Generated 2016-2-2 11:30:39 by Hibernate Tools 3.4.0.CR1


/**
 * Customer generated by hbm2java
 */
public class SysParam implements java.io.Serializable {

  /**
   * 参数编码
   */
  private String paramCode;

  /**
   * 参数名称
   */
  private String paramName;
  /**
   * 参数值
   */
  private String paramValue;
  /**
   * 父参数编码
   */
  private String rootCode;
  /**
   * 描述
   */
  private String des;

  /**
   * 描述
   */
  private Integer rank;

  private String seq;
  /**
   * 是否生效
   */
  private String iseff;
  private Date createTime;
  private Date lastUpdate;


  public SysParam(){
    
  }
  
  public SysParam(String paramCode, String paramName, String paramValue, String rootCode,
      String des, Integer rank, String seq, String iseff, Date createTime, Date lastUpdate) {
    super();
    this.paramCode = paramCode;
    this.paramName = paramName;
    this.paramValue = paramValue;
    this.rootCode = rootCode;
    this.des = des;
    this.rank = rank;
    this.seq = seq;
    this.iseff = iseff;
    this.createTime = createTime;
    this.lastUpdate = lastUpdate;
  }

  public String getParamCode() {
    return paramCode;
  }

  public void setParamCode(String paramCode) {
    this.paramCode = paramCode;
  }

  public String getParamName() {
    return paramName;
  }

  public void setParamName(String paramName) {
    this.paramName = paramName;
  }

  public String getParamValue() {
    return paramValue;
  }

  public void setParamValue(String paramValue) {
    this.paramValue = paramValue;
  }

  public String getRootCode() {
    return rootCode;
  }

  public void setRootCode(String rootCode) {
    this.rootCode = rootCode;
  }

  public String getDes() {
    return des;
  }

  public void setDes(String des) {
    this.des = des;
  }

  public Integer getRank() {
    return rank;
  }

  public void setRank(Integer rank) {
    this.rank = rank;
  }

  public String getSeq() {
    return seq;
  }

  public void setSeq(String seq) {
    this.seq = seq;
  }

  public String getIseff() {
    return iseff;
  }

  public void setIseff(String iseff) {
    this.iseff = iseff;
  }

  public Date getCreateTime() {
    return createTime;
  }

  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  public Date getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

}
