package com.ewing.busi.order.dto;

import com.ewing.core.jdbc.annotation.Column;

// Generated 2016-2-2 17:07:58 by Hibernate Tools 3.4.0.CR1


/**
 * OrderCart generated by hbm2java
 */
public class LightOrderCartResp implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    @Column(fieldName="id")
    private Integer id;
    
    @Column(fieldName="resource_id")
    private Integer resourceId;
    /**
     * 数量
     */
    @Column(fieldName="item_count")
    private Integer itemCount;
    /**
     * 单价
     */
    @Column(fieldName="unit_price")
    private float unitPrice;

    /**
     * 商品名称
     */
    @Column(fieldName="name")
    private String productName;

    /**
     * 头像
     */
    @Column(fieldName="image_url")
    private String icon;

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getResourceId() {
        return resourceId;
    }

    public void setResourceId(Integer resourceId) {
        this.resourceId = resourceId;
    }

    public Integer getItemCount() {
        return itemCount;
    }

    public void setItemCount(Integer itemCount) {
        this.itemCount = itemCount;
    }

    public float getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(float unitPrice) {
        this.unitPrice = unitPrice;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

}
